project/MicroService.scala

This flag was set initially by platops team in template project. From my perspective it's not needed and disturbs in importing project into intellij.
Are they any circumstances why it's here?

now intellij can automatically attach sources to libraries

---

app/uk/gov/hmrc/gform/service/ValidationService.scala
test/uk/gov/hmrc/gform/services/AddressValidationSpec.scala
test/uk/gov/hmrc/gform/services/DateValidationSpec.scala

Fix validation code calling withJSSafeSuffix instead of withSuffix for data validation. Added tests for date and address validation to make sure the right separator is used

Fix bug in date validation introduced by changes in address validation

---

app/uk/gov/hmrc/gform/models/helpers/Javascript.scala

Remove commas and pound signs from numeric values in javascript in order to allow dynamic calculations to be performed on numeric values

Remove commas and pound signs from numeric values

---

app/uk/gov/hmrc/gform/views/summary/TextFormatter.scala
test/uk/gov/hmrc/gform/views/summary/TextFormatterSpec.scala

in summary before adding commas etc.

Remove input pound signs and comma signs from numbers

---

app/uk/gov/hmrc/gform/views/summary/summary.scala.html

This fixes the summary for the Safari browser, in the same way that it was earlier fixed for form sections by Paul in commit 63c59fa9a010fa6dbe651f311eb559d8c64abddc

GFC-52 safari summary fix

---

public/javascripts/gform.js
public/stylesheets/gform.css

Adds a focus class to the label adjacent to the file upload input when the input gains focus. 
This is to show the focus outline for the element in Firefox - this pattern was taken from the upload file button used across GOV.UK - for example uploading a passport photo when applying for a passport.

GFC-285 Adds focus class to upload label for firefox outline

---

app/uk/gov/hmrc/gform/views/form/snippets/choice.scala.html

It seems the element wrapping the radio buttons is preventing certain screen readers from reading the legend associated with the radio buttons when the radio buttons gain focus.

GFC-202 Remove radio buttons wrapping element for screen reader clarity

---

app/uk/gov/hmrc/gform/models/helpers/Javascript.scala

Subtract one number from another in Javascript correctly, GFC-323, rather than incorrectly using reduce()

Subtract one number from another in Javascript correctly

---

app/uk/gov/hmrc/gform/views/form/form.scala.html
public/javascripts/gform.js
public/stylesheets/gform.css

This switches out the back links to be anchor links as opposed to HTML buttons. 
The buttons were causing numerous style issues - and were not working in IE as the button form attribute is not supported in IE yet.

GFC-284 Convert back buttons to links

---

public/stylesheets/gform.css

In removing the styles which altered the default File Upload pattern to be a custom implementation, some required styles for the list of uploaded files was removed. 
This adds back in the required styles.

GFC-356 Re-implement required styles for uploaded file list item/s

---

app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
app/uk/gov/hmrc/gform/models/helpers/Javascript.scala
app/uk/gov/hmrc/gform/summary/SummaryForRender.scala
app/uk/gov/hmrc/gform/views/summary/summary.scala.html
test/uk/gov/hmrc/gform/models/SummarySpec.scala
test/uk/gov/hmrc/gform/models/helpers/JavascriptSpec.scala

Suppress Javascript calculations which are purely static, i.e. dependent only on fields from other sections
Interim
Compiles, needs tests
Add unit tests

Suppress Javascript calculations which are purely static

---

app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
test/uk/gov/hmrc/gform/gform/PrepopServiceSpec.scala

Round Sterling prepopulation calculations to 2 decimal places.
Also unit test rounding in prepopulation (albeit not Sterling per se)

Round Sterling prepopulation calculations to 2 decimal places

---

app/uk/gov/hmrc/gform/gform/FormController.scala
app/uk/gov/hmrc/gform/views/hardcoded/pages/save_acknowledgement.scala.html
conf/app.routes

I have provided a route & action for Save and Exit to delete existing form.  In the past there was a single GET route shared between a form button (in the Start journey) and a link in Save and Exit.  The interaction actually needs to be redesigned and this may be done as part of Agent work

GFC-480 Add reverse route for delete after save and exit

---

test/uk/gov/hmrc/gform/models/helpers/Extractors.scala

GFC-575 Fix a unit test, the date now contains multiple spaces of separation and newline characters.
Sorry @nubz , I found this cause and just fixed it.  I haven't addressed the rather opaque 
https://github.com/hmrc/gform-frontend/blob/1abeb4b0066c448c3a41c550752480ff92b75add/app/uk/gov/hmrc/gform/views/summary/snippets/date.scala.html#L33
which should perhaps be extracted from Twirl

GFC-575 Fix a summary date render unit test

---

app/uk/gov/hmrc/gform/auth/AuthService.scala

Only one of identifiers (not all of them) must match with regimeId

GFC-656 - regimeId check for new HMRC auth

---

app/uk/gov/hmrc/gform/gform/FormController.scala
app/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormComponent.scala

Do not check InfoMessage component when determining where to stop fast forward

GFC-634 - Continue with existing form should fast-forward

---

app/uk/gov/hmrc/gform/models/helpers/Javascript.scala
app/uk/gov/hmrc/gform/submission/SubmissionRef.scala

Stops the error on the 'Bingo duty profits in the return period' page, ensuring the commas are in the right place and the decimal point appears. Need to clarify whether the rounding is acceptable.

GFC-800: Wrapped result of displaySterling function in BigNumber 

---

app/uk/gov/hmrc/gform/auth/AuthService.scala
app/uk/gov/hmrc/gform/gform/FormController.scala
app/uk/gov/hmrc/gform/gform/GformModule.scala
app/uk/gov/hmrc/gform/gform/SummaryController.scala
app/uk/gov/hmrc/gform/gform/handlers/FormControllerRequestHandler.scala
app/uk/gov/hmrc/gform/gform/handlers/FormValidator.scala
app/uk/gov/hmrc/gform/gform/handlers/Redirection.scala
app/uk/gov/hmrc/gform/gform/handlers/package.scala
app/uk/gov/hmrc/gform/obligation/ObligationService.scala
app/uk/gov/hmrc/gform/validation/ValidationService.scala

Remove Future from handler
refactoring => inline few variables
refactoring => extract in to smaller functions step#1
refactoring => generic Monad on updateObligations
Extract more login in to request handler
revert monadless
Extract Html genration from controller
Extract obligations from controller
Extract recalculateDataAndSections from controller
Extract from controller spet#3
form handler wiring
Extract validation form
remove envelopeF fn
remove validate from controller
remove fast forward validation from controller
remove some redundant code
some cleaning up
extract redirect origin
remove implicit global
removing play from request handler
removing play from request handler step#2
removing play from request handler step#3
removing play from request handler step#4

Refactoring FormController

---

app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala

This is reverting work done on "GFORMS-849 - Fix for property
submitMode: derived was displaying"

GFORMS-1202 - £ Persisting through hidden text.

---

app/uk/gov/hmrc/gform/gform/FormController.scala

The change link on ATL items page should be `FastForward.Yes`

GFORMS-1966 - Change behaviour of back link

---

app/uk/gov/hmrc/gform/binders/ValueClassBinder.scala
app/uk/gov/hmrc/gform/gform/FastForwardService.scala
app/uk/gov/hmrc/gform/gform/FormController.scala
app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
app/uk/gov/hmrc/gform/gform/SummaryController.scala
app/uk/gov/hmrc/gform/gform/handlers/FormControllerRequestHandler.scala
app/uk/gov/hmrc/gform/gform/handlers/FormValidator.scala
app/uk/gov/hmrc/gform/gform/processor/FormProcessor.scala
app/uk/gov/hmrc/gform/models/FastForward.scala
app/uk/gov/hmrc/gform/sharedmodel/formtemplate/SectionOrSummary.scala
app/uk/gov/hmrc/gform/summary/SummaryRenderingService.scala

Currently `FastForward.CYA(to: SectionNumber, from: Option[SectionNumber])` assumes that if from is `None` the destination is final CYA page. I refactored to use `Either[CYA.Summary, SectionNumber]` instead of option so that we can have 2 types of CYA pages - one is final and another one is CYA of the task.

GFORMS-1930: TaskList Final and NonFinal CYA pages

---

app/uk/gov/hmrc/gform/gform/processor/FormProcessor.scala
app/uk/gov/hmrc/gform/views/form/addToList.scala.html

fix bugs:
- "Remove" button was missing for all items on repeater page
- After removing last page it jumped to the repeater page instead of the first page or the first iteration

GFORMS-1972: Update ATL so that first item always has a remove link

---

app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala

The 'file' field must be the last field in the submitted form.

GFORMS-1967 - Update interface for upload of files

---

conf/application.conf
public/javascripts/gformSessionTimeout.js

we should update session's timestamp when we post message to a "message-activity" channel. 
If we don't do that the first request /submissions/keep-alive from the dialog if not withing session.timeout will wipe out the session auth header and the next "Save and Continue" will redirect to the auth login.

GFORMS-2062: keep in sync TimeoutDialog timeout and session.timeout

---

app/uk/gov/hmrc/gform/controllers/helpers/FormDataHelpers.scala

- Normalised the entered postcode in the postcode lookup component to fix the issue `Http status: 400, body: {"obj.postcode":[{"msg":["error.invalid"],"args":[]}]}`

GFORMS-2562 - The address-lookup service returns a bad request when unformatted postcode is entered

---

app/uk/gov/hmrc/gform/views/html/package.scala

This reverts commit ec860c99393c8041457661be77dfaf9ecb0df335.

Revert "GFORMS-2496: new form links goes to dashboardClean now (#2105)"

---

app/assets/stylesheets/application.scss
build.sbt
project/plugins.sbt

[warn] WARNING: Your build has 3 bobby warning(s). Please take action to fix these before the listed date, or they will become violations that fail your build [warn]  (1) com.typesafe.sbt:sbt-digest (1.1.4)
[warn]      Reason: Use com.github.sbt:sbt-digest instead
[warn]  (2) com.typesafe.sbt:sbt-uglify (2.0.0)
[warn]      Reason: Use com.github.sbt:sbt-uglify instead
[warn]  (3) net.ground5hark.sbt:sbt-concat (0.2.0)
[warn]      Reason: Use com.github.sbt:sbt-concat instead

Fixing Bobby warnings

---

app/uk/gov/hmrc/gform/eval/EvaluationResults.scala
test/uk/gov/hmrc/gform/eval/EvaluationResultsSpec.scala

Make daysBetween and weeksBetween functions inclusive of start and end dates.
For example:
daysBetween(01042024,01042024) = 1
weeksBetween(01042024,07042024) = 1

GFORMS-3221 fix - Add new functions daysBetween(day1,day2) and weeksBetween(day1,day2) along with ability to sum

---

app/uk/gov/hmrc/gform/models/optics/FormModelVisibilityOptics.scala

BooleanExprResolver should use form phase from evaluation context when evaluating IncludeIf expression

GFORMS-3262 - Allow includeIf on String or en/cy object to evaluate form phase

---

app/uk/gov/hmrc/gform/eval/EvaluationContext.scala
app/uk/gov/hmrc/gform/eval/EvaluationResults.scala
app/uk/gov/hmrc/gform/eval/ExprType.scala
app/uk/gov/hmrc/gform/models/FormModel.scala
app/uk/gov/hmrc/gform/models/OptionDataUtils.scala
app/uk/gov/hmrc/gform/models/TableUtils.scala
app/uk/gov/hmrc/gform/sharedmodel/form/FormModelOptics.scala
build.sbt
test/uk/gov/hmrc/gform/eval/EvaluationResultsSpec.scala
test/uk/gov/hmrc/gform/eval/smartstring/RealSmartStringEvaluatorFactorySpec.scala
test/uk/gov/hmrc/gform/gform/NewFormControllerSpec.scala
test/uk/gov/hmrc/gform/graph/RecalculationSpec.scala
test/uk/gov/hmrc/gform/services/SectionRenderingServiceSpec.scala
test/uk/gov/hmrc/gform/sharedmodel/ExampleData.scala
test/uk/gov/hmrc/gform/summary/SummaryRenderingServiceSpec.scala

Changes made:
1. Removed ExprType.fold abstraction. Abstraction had only 1 use-case, had a potentially negative impact on performance with no benefit to code structure.
2. Changed EvaluationContext.indexedComponentIds type from List[ModelComponentId] to Map[BaseComponentId, List[ModelComponentId]] to improve efficiency of data retrieval (only use-case for this). Time complexity improved from O(n) to O(1).

Gforms-3306 - Performance improvements to gForms frontend for Add to List

---

app/uk/gov/hmrc/gform/validation/TextChecker.scala

{
"_id": "radio-lookup-error",
"formName": "",
"version": 1,
"description": "",
"authConfig": {
"authModule": "anonymous"
},
"sections": [
{
"title": "Tell us about your cash",
"fields": [
{
"id": "cashType",
"type": "text",
"format": "lookup(cashType)",
"label": "cashType"
}
]
}
],
"acknowledgementSection": {
"title": "",
"fields": []
},
"destinations": [
{
"id": "transitionToSubmitted",
"type": "stateTransition",
"requiredState": "Submitted"
}
]
}

GFORMS-3345 - Radio lookup component errors are incorrect 

---

app/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormTemplate.scala
app/uk/gov/hmrc/gform/views/custom/CustomHmrcHeader.scala.html
app/uk/gov/hmrc/gform/views/govuk_wrapper.scala.html
it/test/uk/gov/hmrc/gform/sample/FormTemplateSample.scala
test/uk/gov/hmrc/gform/graph/FormTemplateBuilder.scala
test/uk/gov/hmrc/gform/playcomponents/EmailAuthSessionPurgeFilterSpec.scala
test/uk/gov/hmrc/gform/sharedmodel/ExampleData.scala
test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/FormTemplateGen.scala

Use the updated gov.uk logo and add option to use govuk service navigation component for displaying the form title

GFORMS-3682 - Updates for Implementing GOV.UK design refresh of page header and footers in gForms
