- app/uk/gov/hmrc/bforms/views/address.scala.html
- app/uk/gov/hmrc/bforms/views/choice.scala.html
- app/uk/gov/hmrc/bforms/views/field_template_date.scala.html
- app/uk/gov/hmrc/bforms/views/field_template_text.scala.html
- app/uk/gov/hmrc/bforms/views/form.scala.html
- app/uk/gov/hmrc/bforms/views/snippets/summary/address.scala.html
- app/uk/gov/hmrc/bforms/views/snippets/summary/begin_section.scala.html
- app/uk/gov/hmrc/bforms/views/snippets/summary/choice.scala.html
- app/uk/gov/hmrc/bforms/views/snippets/summary/date.scala.html
- app/uk/gov/hmrc/bforms/views/snippets/summary/end_section.scala.html
- app/uk/gov/hmrc/bforms/views/snippets/summary/text.scala.html
- app/uk/gov/hmrc/bforms/views/summary.scala.html
Modified the HTML to make text, date, address, choice and summary appear as intended
> Styling basic components

- app/uk/gov/hmrc/bforms/views/form.scala.html
- app/uk/gov/hmrc/bforms/views/govuk_wrapper.scala.html
- app/uk/gov/hmrc/bforms/views/summary.scala.html
Adding correct form title and placeholder for correct section title when the templates allow for this
> Page titles and section title placeholder

- app/uk/gov/hmrc/bforms/controllers/FormGen.scala
- app/uk/gov/hmrc/bforms/models/Page.scala
- app/uk/gov/hmrc/bforms/models/Summary.scala
- app/uk/gov/hmrc/bforms/models/components/ComponentType.scala
- app/uk/gov/hmrc/bforms/models/components/FieldValue.scala
- app/uk/gov/hmrc/bforms/models/helpers/Fields.scala
- app/uk/gov/hmrc/bforms/models/helpers/Javascript.scala
- app/uk/gov/hmrc/bforms/views/field_template_text.scala.html
- app/uk/gov/hmrc/bforms/views/snippets/summary/text.scala.html
- test/uk/gov/hmrc/bforms/models/PageSpec.scala
- test/uk/gov/hmrc/bforms/models/SummarySpec.scala
Total option on text component and submitMode option that does readonly and info
> Dave/eeitt 847/text ii

- app/uk/gov/hmrc/gform/views/address.scala.html
- app/uk/gov/hmrc/gform/views/govuk_wrapper.scala.html
Adding placeholder markup for international address
> Adding international address markup

- app/uk/gov/hmrc/gform/views/govuk_wrapper.scala.html
- app/uk/gov/hmrc/gform/views/snippets/summary/begin_section.scala.html
- app/uk/gov/hmrc/gform/views/summary.scala.html
- public/stylesheets/gform.css
Adding a custom styelsheet with initial print styles
> Adding stylesheet and initial print styles

- app/uk/gov/hmrc/gform/controllers/FormGen.scala
- app/uk/gov/hmrc/gform/models/FormFieldValidationResult.scala
- app/uk/gov/hmrc/gform/models/Page.scala
- app/uk/gov/hmrc/gform/models/Section.scala
- app/uk/gov/hmrc/gform/models/Summary.scala
- app/uk/gov/hmrc/gform/models/components/ComponentType.scala
- app/uk/gov/hmrc/gform/models/helpers/Fields.scala
- app/uk/gov/hmrc/gform/service/ValidationService.scala
- app/uk/gov/hmrc/gform/views/form.scala.html
- app/uk/gov/hmrc/gform/views/group.scala.html
- test/uk/gov/hmrc/gform/services/DateValidationSpec.scala
- group render support
- small renames
- display section title (because it was quick to do)
> 938groupinitialrender

- app/uk/gov/hmrc/gform/models/FormFieldValidationResult.scala
- app/uk/gov/hmrc/gform/views/address.scala.html
- app/uk/gov/hmrc/gform/views/field_template_date.scala.html
On behalf of Pawel, until he has permission to push code to fix this:
https://jira.tools.tax.service.gov.uk/browse/EEITT-979
> [EEITT-979] Date component - multiple error messages on separate lines

- test/uk/gov/hmrc/gform/services/DateValidationSpec.scala
(except sometimes around midnight;-)
> Fix date test to work all the year around

- app/uk/gov/hmrc/gform/controllers/testonly/TestOnly.scala
- conf/testOnlyDoNotUseInAppConf.routes
This seems to have fixed the problem Louis was seeing with a routes file not having been compiled after sbt clean.
Googling we found a hint that the controller needs to be in a separate package [https://github.com/playframework/playframework/issues/4430](url)
> Move testOnly to .testonly

- app/uk/gov/hmrc/gform/models/FormFieldValidationResult.scala
- test/uk/gov/hmrc/gform/models/FormFieldValidationResultSpec.scala
Always show last input value in Date component if there was one
> Eeitt 1043

- app/uk/gov/hmrc/gform/models/Section.scala
- app/uk/gov/hmrc/gform/models/Summary.scala
- test/uk/gov/hmrc/gform/models/PageSpec.scala
- test/uk/gov/hmrc/gform/models/SummarySpec.scala
New shortName field added to Section, modified Summary to use this if available, normal title if not
The gform microservice was also modified, branch with the same name.
> New shortName field added to Section

- app/uk/gov/hmrc/gform/models/components/ComponentType.scala
- app/uk/gov/hmrc/gform/models/components/FieldId.scala
- app/uk/gov/hmrc/gform/service/ValidationService.scala
- app/uk/gov/hmrc/gform/views/field_template_address.scala.html
- public/javascripts/gform.js
Replace dots in input names and ids to something HTML-compliant
Requires fix in gform repo, branch same name
> EEITT-1078 - Replace dots in input names and ids to something HTML-compliant

- app/uk/gov/hmrc/gform/models/components/ComponentType.scala
- app/uk/gov/hmrc/gform/models/components/FieldId.scala
- app/uk/gov/hmrc/gform/service/ValidationService.scala
- app/uk/gov/hmrc/gform/views/field_template_address.scala.html
- public/javascripts/gform.js
Reverts hmrc/gform-frontend#42 (build fails)
> Revert "EEITT-1078 - Replace dots in input names and ids to something HTML-compliant"

- app/uk/gov/hmrc/gform/GuiceModule.scala
- app/uk/gov/hmrc/gform/auth/AuthModule.scala
> auth module

- app/uk/gov/hmrc/gform/GuiceModule.scala
- app/uk/gov/hmrc/gform/config/config.scala
- app/uk/gov/hmrc/gform/config/frontendAppConfig.scala
- app/uk/gov/hmrc/gform/controllers/package.scala
- app/uk/gov/hmrc/gform/dev/GuiceModule.scala
- app/uk/gov/hmrc/gform/dev/gformAuthenticationProvider.scala
- app/uk/gov/hmrc/gform/models/FormFieldValidationResult.scala
- app/uk/gov/hmrc/gform/service/ValidationService.scala
- conf/application.conf
- project/FrontendBuild.scala
- test/uk/gov/hmrc/gform/config/AppConfigSpec.scala
Rename bforms to bform, correct spelling of gform as one word and remove Mongo
> Dave/eeitt 849/rename bforms remove mongo

- app/uk/gov/hmrc/gform/connectors/GformConnector.scala
- app/uk/gov/hmrc/gform/controllers/FormGen.scala
- app/uk/gov/hmrc/gform/service/SaveService.scala
removed saveForm logic (we need only update form data)
> removed saveForm logic (we need only update form data)

- app/uk/gov/hmrc/gform/controllers/FormController.scala
- app/uk/gov/hmrc/gform/models/Page.scala
- app/uk/gov/hmrc/gform/models/PageShader.scala
- app/uk/gov/hmrc/gform/models/Section.scala
- app/uk/gov/hmrc/gform/views/confirm_delete.scala.html
- app/uk/gov/hmrc/gform/views/form.scala.html
- conf/app.routes
- test/uk/gov/hmrc/gform/gformbackend/GformConnectorSpec.scala
- test/uk/gov/hmrc/gform/models/BooleanExprSpec.scala
- test/uk/gov/hmrc/gform/models/PageForRenderSpec.scala
- test/uk/gov/hmrc/gform/models/PageSpec.scala
- test/uk/gov/hmrc/gform/models/SummarySpec.scala
the description was not being persisted and displayed on the relevant section.
> Eeitt 969/add description

- app/uk/gov/hmrc/gform/validation/ValidationService.scala
with original error message text
> Satisfy acceptance tests for non-numeric text fields

- app/uk/gov/hmrc/gform/auditing/AuditingModule.scala
This fixes auditing hang up on submission due to recursion. Thanks to tenoch for finding it.
> stopping recursion in the code for auditConnector

- app/uk/gov/hmrc/gform/controllers/FormController.scala
- app/uk/gov/hmrc/gform/controllers/SummaryGen.scala
- app/uk/gov/hmrc/gform/models/Page.scala
- app/uk/gov/hmrc/gform/models/PageShader.scala
- app/uk/gov/hmrc/gform/models/Section.scala
- app/uk/gov/hmrc/gform/models/Summary.scala
- app/uk/gov/hmrc/gform/service/RepeatingComponentService.scala
- test/uk/gov/hmrc/gform/gformbackend/GformConnectorSpec.scala
- test/uk/gov/hmrc/gform/models/BooleanExprSpec.scala
- test/uk/gov/hmrc/gform/models/PageForRenderSpec.scala
- test/uk/gov/hmrc/gform/models/PageSpec.scala
- test/uk/gov/hmrc/gform/models/SummarySpec.scala
- test/uk/gov/hmrc/gform/services/AddressValidationSpec.scala
- test/uk/gov/hmrc/gform/services/DateValidationSpec.scala
- test/uk/gov/hmrc/gform/services/NumberValidationSpec.scala
I am trying to avoid a massive PR
This is some initial work to support repeating sections on the frontend
> EEiTT-866 - Initial work to support repeating sections

- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/BooleanExpr.scala
ooops, I missed some importants .... sorry for premature merge
> Revert "back button now does includeif on the previous page to remember to sh…"

- app/uk/gov/hmrc/gform/models/PageShader.scala
- app/uk/gov/hmrc/gform/models/helpers/Javascript.scala
- app/uk/gov/hmrc/gform/views/collapsable.scala.html
> fixed the collaping group showing on summary

- project/FrontendBuild.scala
> Library version bumps

- app/uk/gov/hmrc/gform/auditing/AuditService.scala
- app/uk/gov/hmrc/gform/auth/EeittAuthorisationDelegate.scala
- app/uk/gov/hmrc/gform/auth/models/AuthResult.scala
- app/uk/gov/hmrc/gform/controllers/AcknowledgementController.scala
- app/uk/gov/hmrc/gform/controllers/AuthenticatedRequestActions.scala
- app/uk/gov/hmrc/gform/controllers/DeclarationController.scala
- app/uk/gov/hmrc/gform/controllers/FormController.scala
- app/uk/gov/hmrc/gform/controllers/SummaryGen.scala
- app/uk/gov/hmrc/gform/fileupload/FileUploadController.scala
- app/uk/gov/hmrc/gform/prepop/PrepopService.scala
- app/uk/gov/hmrc/gform/service/SectionRenderingService.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/AuthConfig.scala
- test/uk/gov/hmrc/gform/services/SectionRenderingServiceSpec.scala
Getting rid of confusing implicits
> Auth refactoring - Two params are now passed to actions, request and a cache

- app/uk/gov/hmrc/gform/views/form/snippets/field_template_file_upload.scala.html
Fixes a bug where the upload link is not visible when JS is disabled and an error occurs uploading the first document
> [EEITT-1344] File upload non-js error bug

- app/uk/gov/hmrc/gform/controllers/Direction.scala
- app/uk/gov/hmrc/gform/gform/FormController.scala
- app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
- app/uk/gov/hmrc/gform/views/form/form.scala.html
Fix display of and navigation to first section, allowing for IncludeIf and correct control of display of back button
> Fix display of and navigation to first section, allowing for IncludeIf

- app/uk/gov/hmrc/gform/views/hardcoded/pages/save_acknowledgement.scala.html
The content of the save for later acknowledgement was a mock up.
This replaces the content with something agreed by Ann Cooke
> Dave/gfc 86/save content 2

- app/uk/gov/hmrc/gform/gform/DeclarationController.scala
Fix customer id from expression referencing data field value, using data field values from the form sections, not just from the declaration
> Fix customer id from expression referencing data field value again

- app/uk/gov/hmrc/gform/auditing/AuditService.scala
- app/uk/gov/hmrc/gform/auth/AuthModule.scala
- app/uk/gov/hmrc/gform/auth/AuthService.scala
- app/uk/gov/hmrc/gform/controllers/AuthenticatedRequestActions.scala
- app/uk/gov/hmrc/gform/gform/AcknowledgementController.scala
- app/uk/gov/hmrc/gform/gform/DeclarationController.scala
- app/uk/gov/hmrc/gform/gform/EeittService.scala
- app/uk/gov/hmrc/gform/gform/GformModule.scala
- app/uk/gov/hmrc/gform/gform/PrepopService.scala
- test/uk/gov/hmrc/gform/gform/EeittServiceSpec.scala
- test/uk/gov/hmrc/gform/gform/PrepopServiceSpec.scala
Evaluate eeitt context variables from the eeitt service for customeId at declaration
> Evaluate eeitt context variables from the eeitt service

- app/uk/gov/hmrc/gform/models/helpers/Javascript.scala
GFC-322 implement subtraction of a product in javaScript as a special case (and addition too)
> GFC-322 implement subtraction of a product in javaScript as a special case

- app/uk/gov/hmrc/gform/views/summary/snippets/text.scala.html
Fixes alignment issues with the summary page.
> GFC-416 summary page layout tweaks

- app/uk/gov/hmrc/gform/gform/PrepopService.scala
- app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
- app/uk/gov/hmrc/gform/keystore/RepeatingComponentService.scala
- app/uk/gov/hmrc/gform/models/helpers/Javascript.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/ComponentType.scala
- test/uk/gov/hmrc/gform/models/helpers/JavascriptSpec.scala
Let's prefer lift function into a `Future` rather than threading `Future` throughout it as parameters.
> Javascript generation doesn't need to depend on a Future

- app/uk/gov/hmrc/gform/views/form/snippets/field_template_info.scala.html
Have updated warning message to match those with latest on GovElements.
> Amendment to importantInfo gov elements pattern

- app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
GFC-473 Revert 1d4dbe8b - GFC-349 Multiline Input - support for value and format attribute - prepop
> GFC-473 avoid problems with groups: revert 1d4dbe8b - GFC-349 Multiline prepop

- app/uk/gov/hmrc/gform/models/helpers/Fields.scala
sbt test shows no failures after change
> GFC-436: removed erroneous filter from formFields map

- app/uk/gov/hmrc/gform/validation/ValidationService.scala
- test/uk/gov/hmrc/gform/services/NumberValidationSpec.scala
> GFC-541: remove commas when computing size of number

- app/uk/gov/hmrc/gform/gform/FormController.scala
- app/uk/gov/hmrc/gform/summary/SummaryForRender.scala
> GFC-33 Eliminate Keystore - skip empty groups take 2 and mandatory

- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/ADTFormat.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormTemplate.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/Destination.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/HttpMethod.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/Profile.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormTemplateSpec.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/DestinationsSpec.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/HttpMethodSpec.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/ProfileSpec.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/package.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/DestinationGen.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/DestinationsGen.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/FormGen.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/HttpMethodGen.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/PrimitiveGen.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/ProfileGen.scala
Not quite finished yet. Pushing for preliminary testing.
> GFC-624: handlebarsHttpApi destination - excluding magicCommas

- app/uk/gov/hmrc/gform/controllers/AuthenticatedRequestActions.scala
- app/uk/gov/hmrc/gform/gform/FormController.scala
- app/uk/gov/hmrc/gform/validation/ValidationService.scala
Fix for template with section including computed field only
> GFC-634 - Continue with existing form should fast-forward

- app/uk/gov/hmrc/gform/views/form/snippets/field_template_address.scala.html
- public/javascripts/gformToggleAddressLabels.js
Rdb/gfc 748/address component not clear postcode when toggling
> Rdb/gfc 748/address component not clear postcode when toggling

- app/uk/gov/hmrc/gform/auditing/AuditService.scala
- app/uk/gov/hmrc/gform/auth/models/MaterialisedRetrievals.scala
- app/uk/gov/hmrc/gform/gform/AcknowledgementController.scala
- app/uk/gov/hmrc/gform/gform/DeclarationController.scala
- app/uk/gov/hmrc/gform/gform/PrepopService.scala
- app/uk/gov/hmrc/gform/graph/Recalculation.scala
- app/uk/gov/hmrc/gform/graph/processor/UserCtxEvaluatorProcessor.scala
- app/uk/gov/hmrc/gform/models/mappings/ServiceNameAndTaxId.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/Expr.scala
- test/uk/gov/hmrc/gform/auth/AuthServiceSpec.scala
- test/uk/gov/hmrc/gform/gformbackend/GformConnectorSpec.scala
- test/uk/gov/hmrc/gform/graph/RecalculationSpec.scala
- test/uk/gov/hmrc/gform/graph/processor/UserCtxEvaluatorProcessorTest.scala
- test/uk/gov/hmrc/gform/sharedmodel/SubmissionReferenceSpec.scala
Evaluate EnrolledIdentifier
Evaluate EnrolledIdentifier test
Extract UserCtx logic out of Recalculator
Test each user CTX with generator
Replace strings with ADT
Revert passing ServiceId to EnrolmentIdentifier
Revert serviceId as part of EnrolmentIdentifier
Fix conflict
Fix conflict V_3
> Add EnrolledIdentifier

- app/uk/gov/hmrc/gform/controllers/AuthenticatedRequestActions.scala
- app/uk/gov/hmrc/gform/gformbackend/GformConnector.scala
removed duplicate input parameter to be included within the function
removed duplicate input parameter to be included within the function
removed incorrect merge imports
> removed whitelist PLEASE DO NOT MERGE YET 

- app/uk/gov/hmrc/gform/views/form/snippets/collapsable.scala.html
replaced panel-border-narrow with panel-indend to center panel border
> Update collapsable.scala.html as per standard

- app/uk/gov/hmrc/gform/config/ConfigModule.scala
- app/uk/gov/hmrc/gform/config/FrontendAppConfig.scala
- app/uk/gov/hmrc/gform/gform/DeclarationController.scala
- app/uk/gov/hmrc/gform/gformbackend/GformConnector.scala
- test/uk/gov/hmrc/gform/graph/RecalculationSpec.scala
- test/uk/gov/hmrc/gform/sharedmodel/ExampleData.scala
- test/uk/gov/hmrc/gform/sharedmodel/SubmissionReferenceSpec.scala
> removed send-pdf-with-submission along with all references PLEASE DO NOT MERGE YET 

- app/uk/gov/hmrc/gform/gform/DeclarationController.scala
- app/uk/gov/hmrc/gform/gform/GformSubmission.scala
- app/uk/gov/hmrc/gform/gformbackend/GformConnector.scala
- app/uk/gov/hmrc/gform/graph/processor/IdentifierExtractor.scala
- app/uk/gov/hmrc/gform/graph/processor/UserCtxEvaluatorProcessor.scala
- app/uk/gov/hmrc/gform/sharedmodel/SubmissionData.scala
- app/uk/gov/hmrc/gform/sharedmodel/Variables.scala
- app/uk/gov/hmrc/gform/sharedmodel/VariablesBuilder.scala
- app/uk/gov/hmrc/gform/sharedmodel/package.scala
- project/Dependencies.scala
- project/plugins.sbt
- test/pact/uk/gov/hmrc/gform/GFormConnectorPactTest.scala
- test/uk/gov/hmrc/gform/gform/VariablesBuilderTest.scala
- test/uk/gov/hmrc/gform/graph/processor/IdentifierExtractorTest.scala
- test/uk/gov/hmrc/gform/graph/processor/UserCtxEvaluatorProcessorTest.scala
- test/uk/gov/hmrc/gform/sharedmodel/SubmissionDataTest.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/FormTemplateGen.scala
Add variable key
Add json serializer
Extract some logic from controller
Add SubmissionData to submitFormWithPdf
Wire in submission data with POST request
Use Lenses to update nested case classes
Add regime id filter
Extract IdentifierExtractor in to different file
use play macro for json
Pact test
Pact test + refactoring
Just a renaming
Resolved conflict
Revert a change
Resolve more conflicts again
> Build a data structure with data needed to gform

- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormatExpr.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/FormatExprGen.scala
an unused variable was found while working on handlebars tests, removed as lanced requested.
> [no-GFC][DC] removed unused variable

- app/uk/gov/hmrc/gform/models/ExpandUtils.scala
removed multi-field based typing within nonSubmitted as they was being submitted twice.
> GFC-780][DC & KC] removed duplicated fields 

- app/uk/gov/hmrc/gform/gform/AcknowledgementController.scala
- app/uk/gov/hmrc/gform/gform/DeclarationController.scala
Now deals with groups when adding information to the pdf
> Gfc 790/sm/deal with groups

- app/uk/gov/hmrc/gform/gform/FormController.scala
- app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
- app/uk/gov/hmrc/gform/graph/Recalculation.scala
- app/uk/gov/hmrc/gform/models/ObligationValidator.scala
- app/uk/gov/hmrc/gform/models/ProcessData.scala
- app/uk/gov/hmrc/gform/models/TaxPeriodStateChecker.scala
- app/uk/gov/hmrc/gform/models/TaxSelectionNavigator.scala
- app/uk/gov/hmrc/gform/models/gform/ObligationsAction.scala
- app/uk/gov/hmrc/gform/models/gform/UserType.scala
- app/uk/gov/hmrc/gform/sharedmodel/TaxPeriods.scala
- app/uk/gov/hmrc/gform/sharedmodel/graph/DependecyGraph.scala
- test/uk/gov/hmrc/gform/graph/DependencyGraphSpec.scala
- test/uk/gov/hmrc/gform/models/ObligationValidatorTest.scala
- test/uk/gov/hmrc/gform/models/ObligationValidatorTestFixture.scala
- test/uk/gov/hmrc/gform/models/TaxPeriodStateCheckerTest.scala
- test/uk/gov/hmrc/gform/models/TaxSelectionNavigatorTest.scala
Just a renaming
Extract some functionality
Add returning user flag
> GFC-796 - hmrcTaxPeriodSelector save and come back later behaviour

- app/uk/gov/hmrc/gform/gform/AcknowledgementController.scala
- app/uk/gov/hmrc/gform/gform/DeclarationController.scala
- app/uk/gov/hmrc/gform/sharedmodel/form/DestinationSubmissionInfo.scala
- app/uk/gov/hmrc/gform/sharedmodel/form/Form.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormTemplate.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/Destination.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/Destinations.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/destinations/HandlebarsTemplateProcessorModel.scala
- app/uk/gov/hmrc/gform/sharedmodel/structuredform/Field.scala
- app/uk/gov/hmrc/gform/sharedmodel/structuredform/StructuredFormValue.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormTemplateSpec.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/DestinationSubmissionInfoGen.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/generators/FormGen.scala
We want to get this merged into master because there are quite a few changes
> GFC-889: gForms submission to form review service

- app/uk/gov/hmrc/gform/LookupLoader.scala
- app/uk/gov/hmrc/gform/gform/DeclarationController.scala
- app/uk/gov/hmrc/gform/gform/LookupController.scala
- app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
- app/uk/gov/hmrc/gform/gform/StructuredFormDataBuilder.scala
- app/uk/gov/hmrc/gform/graph/Recalculation.scala
- app/uk/gov/hmrc/gform/lookup/LocalisedLookupOptions.scala
- app/uk/gov/hmrc/gform/lookup/LookupType.scala
- app/uk/gov/hmrc/gform/validation/ComponentValidator.scala
- app/uk/gov/hmrc/gform/views/form/snippets/lookup_autosuggest.scala.html
- app/uk/gov/hmrc/gform/views/form/snippets/lookup_radios.scala.html
- project/Dependencies.scala
- test/uk/gov/hmrc/gform/gform/StructuredFormDataBuilderSpec.scala
- test/uk/gov/hmrc/gform/graph/RecalculationSpec.scala
GFC-914 - Welsh support for lookup content
GFC-943 - Update Cash Dec form template to use orElse operator
>  GFC-914 / GFC-943

- conf/app.routes
> GFC-1076 - "Print or save a PDF copy of your answers" link on

- app/uk/gov/hmrc/gform/gformbackend/GformConnector.scala
User is unable to save or print the PDF after successful submission
> GFC-1124 - BAU Live Support

- app/uk/gov/hmrc/gform/validation/ValidationService.scala
It was possible to submit completely empty form
> GFORMS-231 - Access Forbidden – 4.5%

- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/FormTemplate.scala
- app/uk/gov/hmrc/gform/views/form/form.scala.html
- app/uk/gov/hmrc/gform/views/specimen/navigation.scala.html
> GFORMS-276 - Accessibility automation feature step

- app/uk/gov/hmrc/gform/auth/SelfEmployedIncomeSupportEligibilityConnector.scala
- app/uk/gov/hmrc/gform/validation/ComponentValidator.scala
- conf/messages
- conf/messages.cy
Signed-off-by: Sandip Khedekar <Sandip.Khedekar16@gmail.com>
> GFORMS-825 - UTR validations improvement

- app/uk/gov/hmrc/gform/eval/BooleanExprEval.scala
- app/uk/gov/hmrc/gform/eval/ExpressionResult.scala
- app/uk/gov/hmrc/gform/eval/ExpressionResultWithTypeInfo.scala
- app/uk/gov/hmrc/gform/models/FormModelBuilder.scala
- app/uk/gov/hmrc/gform/models/optics/FormModelVisibilityOptics.scala
When "value expression" evaluates as Hidden, but we need to shown it
on the page we need some default values
> GFORMS-913 - default value for Hidden expressions when displayed

- app/uk/gov/hmrc/gform/controllers/Direction.scala
- app/uk/gov/hmrc/gform/eval/AllPageModelExpressions.scala
- app/uk/gov/hmrc/gform/eval/StandaloneSumInfo.scala
- app/uk/gov/hmrc/gform/gform/EnrolmentController.scala
- app/uk/gov/hmrc/gform/gform/FormController.scala
- app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
- app/uk/gov/hmrc/gform/gform/StructuredFormDataBuilder.scala
- app/uk/gov/hmrc/gform/gform/processor/EnrolmentResultProcessor.scala
- app/uk/gov/hmrc/gform/gform/processor/package.scala
- app/uk/gov/hmrc/gform/instructions/InstructionsRenderingService.scala
- app/uk/gov/hmrc/gform/models/AddToListUtils.scala
- app/uk/gov/hmrc/gform/models/Bracket.scala
- app/uk/gov/hmrc/gform/models/BracketPlain.scala
- app/uk/gov/hmrc/gform/models/BracketsWithSectionNumber.scala
- app/uk/gov/hmrc/gform/models/FormModel.scala
- app/uk/gov/hmrc/gform/models/FormModelBuilder.scala
- app/uk/gov/hmrc/gform/models/FormModelExpander.scala
- app/uk/gov/hmrc/gform/models/PageModel.scala
- app/uk/gov/hmrc/gform/models/RepeaterWithNumber.scala
- app/uk/gov/hmrc/gform/models/SingletonWithNumber.scala
- app/uk/gov/hmrc/gform/models/ids/ModelComponentId.scala
- app/uk/gov/hmrc/gform/sharedmodel/form/FormModelOptics.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/Section.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/SectionNumber.scala
- app/uk/gov/hmrc/gform/summary/SummaryRenderingService.scala
- app/uk/gov/hmrc/gform/views/form/addToList.scala.html
- test/uk/gov/hmrc/gform/graph/DependencyGraphSpec.scala
- test/uk/gov/hmrc/gform/models/FormModelSpec.scala
Most important in this PRs is change in `FormModel` where
```
pagesWithIndex: List[(PageModel[A], SectionNumber)],
```
has been superseeded by:
```
brackets: BracketsWithSectionNumber[A],
```
`BracketsWithSectionNumber` holds data about where pages in the form comes from, ie. from NonRepeating section, Repeating section or from Add To List.
> Bracket model introduction

- app/uk/gov/hmrc/gform/gform/StructuredFormDataBuilder.scala
- test/uk/gov/hmrc/gform/gform/StructuredFormDataBuilderSpec.scala
Don't include Groups and Infos
> GFORMS-913 - Handlebar/RoboticsXml model improvements

- app/assets/stylesheets/application.scss
- app/uk/gov/hmrc/gform/gform/SectionRenderingService.scala
- app/uk/gov/hmrc/gform/summary/SummaryRenderingService.scala
- app/uk/gov/hmrc/gform/views/form/addToList.scala.html
1. Added support for markdown in add-to-list description attribute
2. Updated width to occupy maximum space
> GFORMS-985 Improved formatting in add-to-list summary section

- app/uk/gov/hmrc/gform/controllers/helpers/FormDataHelpers.scala
- app/uk/gov/hmrc/gform/models/FormModel.scala
- app/uk/gov/hmrc/gform/ops/package.scala
- app/uk/gov/hmrc/gform/validation/ValidationResult.scala
so validation can see UpperCased values where defined
> GFORMS-913 - fix IsUpperCase to have immediate effect

- app/uk/gov/hmrc/gform/gform/FormController.scala
- app/uk/gov/hmrc/gform/models/FormModel.scala
will show first preceding visible page if such a page exists otherwise
first visible page will be shown
> GFORMS-913 - Trying to access an invisible page

- app/uk/gov/hmrc/gform/models/FormComponentVisibilityFilter.scala
- app/uk/gov/hmrc/gform/models/FormModel.scala
- app/uk/gov/hmrc/gform/models/FormModelBuilder.scala
- app/uk/gov/hmrc/gform/models/VisibilityFilter.scala
- project/Dependencies.scala
Validation fixes for revealing choice and group components
> GFORMS-383 - Introduce IncludeIf functionality at field level

- app/uk/gov/hmrc/gform/controllers/AuthenticatedRequestActions.scala
- app/uk/gov/hmrc/gform/controllers/GformSessionSupport.scala
- app/uk/gov/hmrc/gform/controllers/GformSessionSyntax.scala
- app/uk/gov/hmrc/gform/gform/AcknowledgementController.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/ReferrerConfig.scala
- test/uk/gov/hmrc/gform/sharedmodel/formtemplate/ReferrerConfigSpec.scala
1. ReferrerConfig exitMessage localized
2. Clear auth entries from session after displaying acknowledgement page
> GFORMS-1177 ReferrerConfig exitMessage localized. 

- app/uk/gov/hmrc/gform/views/form/addToList.scala.html
As <span> is an inline element and <p> being a block element is not allowed inside <span>
> GFORMS-1249 Replaced span with div in add to list summary

- app/uk/gov/hmrc/gform/sharedmodel/graph/DependencyGraph.scala
- test/uk/gov/hmrc/gform/graph/DependencyGraphSuite.scala
Preparation work for GFORMS-1714
> DependencyGraph - handle references to atl field from outside atl

- app/uk/gov/hmrc/gform/models/FormModel.scala
- app/uk/gov/hmrc/gform/tasklist/TaskListController.scala
> GFORMS-1770 - Enhance task summary / CYA to be optional and configurable

- app/uk/gov/hmrc/gform/controllers/Navigation.scala
- app/uk/gov/hmrc/gform/models/FastForward.scala
- test/uk/gov/hmrc/gform/controllers/NavigationSpec.scala
next section should not skip ATL non repeater section if comes from within ATL
> GFORMS-1788: ATL change FF bug fix

- app/uk/gov/hmrc/gform/summary/SummaryRenderingService.scala
the table summary in the CYA page
> GFORMS-1961: AC4 implementation

- Navigation.md
- app/uk/gov/hmrc/gform/gform/SummaryController.scala
in the task with a summary page, when click change from the main CYA and then click back button, then we should go to the main CYA.
> GFORMS-1997: task list bug fix

- Navigation.md
- app/uk/gov/hmrc/gform/gform/FastForwardService.scala
- app/uk/gov/hmrc/gform/tasklist/TaskListController.scala
the original implementation in v0.1282.0 introduced regression.
this is a reverse of v0.1282.0 and reimplentation.
> GFORMS-2056: reimplentation with bug fix

- app/uk/gov/hmrc/gform/gform/AcknowledgementController.scala
- Fixed issue with versioning when clicking the download pdf link on the acknowledgement page
> GFORMS-2209- Sprint 97 release activities

- app/uk/gov/hmrc/gform/gform/FastForwardService.scala
- app/uk/gov/hmrc/gform/validation/ValidationService.scala
- Removed verifying validations and sending email for all sections in fast forward
> GFORMS-2195 - Sprint 96 release activities

- app/uk/gov/hmrc/gform/models/Bracket.scala
defined not on all iteration's sections
> GFORMS-2288: only check removeItemIf on the section where it is

- app/uk/gov/hmrc/gform/controllers/ErrorHandler.scala
- Changed the logger level from ERROR to INFO
> GFORMS-2341 - Sprint 102 release activities

- app/uk/gov/hmrc/gform/gform/FormController.scala
Reverts hmrc/gform-frontend#2004
> Revert "GFORMS-2428 - When using postcodeLookup an invalid postcode blocks us…"

- app/uk/gov/hmrc/gform/eval/EvaluationResults.scala
{
"_id": "dest-contact-details-address",
"version": 1,
"formName": "Name of service",
"description": "DES Contract details address",
"authConfig": {
"authModule": "hmrc"
},
"sections": [
{
"title": "Contact details",
"fields": [
{
"type": "text",
"id": "agent",
"label": "Agent ref number",
"format": "text"
}
],
"dataRetrieve": [
{
"type": "agentDetails",
"id": "agencyInfo",
"parameters": {
"agentReferenceNumber": "${agent}"
}
}
]
},
{
"title": "Contact details",
"fields": [
{
"type": "info",
"id": "info1",
"label": {
"en": "",
"cy": ""
},
"infoType": "noformat",
"infoText": "Agency Address: ${dataRetrieve.agencyInfo.agencyAddress}"
}
]
}
],
"acknowledgementSection": {
"title": "Confirmation page",
"fields": []
},
"destinations": [
{
"id": "transitionToSubmitted",
"type": …
> GFORMS-3026 - Update data retrieval to correct response from DES

- app/uk/gov/hmrc/gform/controllers/helpers/FormDataHelpers.scala
> GFORMS-2742 - Validation not allowing user add spaces between characters (P1)

- app/uk/gov/hmrc/gform/builder/BuilderController.scala
- app/uk/gov/hmrc/gform/eval/AllPageModelExpressionsGetter.scala
- app/uk/gov/hmrc/gform/gform/FormAddToListController.scala
- app/uk/gov/hmrc/gform/gform/FormController.scala
- app/uk/gov/hmrc/gform/gform/processor/FormProcessor.scala
- app/uk/gov/hmrc/gform/models/Bracket.scala
- app/uk/gov/hmrc/gform/models/FormModel.scala
- app/uk/gov/hmrc/gform/models/FormModelBuilder.scala
- app/uk/gov/hmrc/gform/models/SingletonWithNumber.scala
- app/uk/gov/hmrc/gform/summary/SummaryRenderingService.scala
- app/uk/gov/hmrc/gform/views/debug/modelOptic.scala.html
Move defaultPage to more convenient place in model
> GFORMS-3005 - Refactor SectionNumber to be more predictable

- app/uk/gov/hmrc/gform/gform/NewFormController.scala
> GFORMS-3207 - Regression Bug due to GFORMS-2733

- app/uk/gov/hmrc/gform/validation/DateChecker.scala
- test/uk/gov/hmrc/gform/validation/DateCheckerSpec.scala
```
{
"_id": "date-issue",
"formName": "Name of the service",
"description": "",
"version": 1,
"authConfig": {
"authModule": "hmrc"
},
"sections": [
{
"title": "Information",
"fields": [
{
"id": "whenStartScheme",
"label": "test",
"type": "date",
"format": "after today-50",
"shortName": "Start date",
"errorShortName": "start date",
"errorShortNameStart": "Start date",
"helpText": "For example, 13 4 2025."
}
]
}
],
"declarationSection": {
"title": "Declaration",
"shortName": "Declaration",
"fields": [
]
},
"acknowledgementSection": {
"title": "Acknowledgement Page",
"fields": []
},
"destinations": [
{
"id": "transitionToSubmitted",
"type": "stateTransition",
"requiredState": "Submitted"
}
]
}
```
> GFORMS-3251 - Production Issue-Date error message

- app/uk/gov/hmrc/gform/gform/NewFormController.scala
If the user's language is set to Welsh but the form is English only, change the language set to English
> GFORMS-3275 - Welsh is showing for users when toggle is not available

- app/uk/gov/hmrc/gform/auth/AuthLoginStubConnector.scala
- app/uk/gov/hmrc/gform/testonly/TestOnlyController.scala
This reverts commit 1ea66a613f0b9efe8d577f00b1733eaf8288ac7f.
> Revert "GFORMS-3353 - snapshot session issue (#2475)"

- app/uk/gov/hmrc/gform/testonly/TestOnlyController.scala
- app/uk/gov/hmrc/gform/views/debug/viewExpressions.scala.html
expressions table in toolbox.
Add fields table on toolbox expressions page.
> GFORMS-3007 - Add type, round, fractional digits and result type columns to… 

- app/uk/gov/hmrc/gform/eval/EvaluationResults.scala
- app/uk/gov/hmrc/gform/eval/smartstring/SmartStringEvaluatorFactory.scala
- app/uk/gov/hmrc/gform/gform/ConcatFormatSubstituter.scala
- app/uk/gov/hmrc/gform/gform/ExprUpdater.scala
- app/uk/gov/hmrc/gform/gform/FormComponentIdSubstituter.scala
- app/uk/gov/hmrc/gform/gform/SummaryExprSubstituter.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/Expr.scala
- app/uk/gov/hmrc/gform/sharedmodel/formtemplate/ExprPrettyPrint.scala
- test/uk/gov/hmrc/gform/eval/smartstring/RealSmartStringEvaluatorFactorySpec.scala
Added:
bulletedListChoicesSelected
numberedListChoicesSelected
that will evaluate inside/outside ATL
> GFORMS-3309 - In ATL add functions that allows designer to replay choices already selected on same page as the choice
